package com.devkit.applications.rest;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Request DTO for creating or setting an encryption key for an application.
 */
public record CreateEncryptionKeyRequest(

    @Size(min = 32, message = "Encryption key must be at least 32 characters")
    String key,

    @NotBlank(message = "User email is required for audit")
    @jakarta.validation.constraints.Email(message = "User email must be valid")
    String createdBy
) {
    /**
     * Factory method for auto-generating a key.
     * If key is null or empty, a random key will be generated by the service.
     */
    public static CreateEncryptionKeyRequest withAutoGeneratedKey(String createdBy) {
        return new CreateEncryptionKeyRequest(null, createdBy);
    }
}
