package com.devkit.applications.rest;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Request DTO for rotating an application's encryption key.
 */
public record RotateEncryptionKeyRequest(

    @NotBlank(message = "User email is required for audit")
    @Email(message = "User email must be valid")
    String rotatedBy,

    @Size(min = 32, message = "Encryption key must be at least 32 characters")
    String newKey
) {
    /**
     * Factory method for auto-generating a new key during rotation.
     * If newKey is null or empty, a random key will be generated by the service.
     */
    public static RotateEncryptionKeyRequest withAutoGeneratedKey(String rotatedBy) {
        return new RotateEncryptionKeyRequest(rotatedBy, null);
    }
}
